version: '3.1'
services:
  app:
    container_name: docker-spring-java-boilerplace
    image: docker-spring-java-boilerplace
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5434:5434"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=register